### ISSUE TITLE
fix(tests,mesh): restore the bindings #642 dropped and bring the suite onto the complex conventions

### ISSUE THREAD

**Issue by akellehe** [akellehe/tessera#644]
## Goal

`pytest tests/` is green again on `manual-fixes-for-multicobordism`. The
complexified-Regge merge (#642) left 232 failing tests. They fall into three
groups, and only the first is a defect in the shipped code.

## Group 1 — a regression introduced by #642 (fix the code, not the tests)

Ten `Simplex` pybind entries were deleted by an over-greedy regular expression
that was meant to remove only the `dihedralAngle` binding. It matched from
`dihedralAngle` all the way to `lorentzianDihedralAngle` and swallowed
everything between:

`area`, `volume`, `volumeGradient`, `circumcenterBarycentric`,
`circumradiusSquared`, `dualVolume`, `dualVolumeGradient`, `dualVolumeHessian`,
`hasTopCoface`, `hodgeStar`

All ten still exist in C++ and are simply unreachable from Python. This accounts
for a large share of the 232 and explains both failures previously suspected of
being physics regressions:

- `test_dual_volume_signs_python` — `AttributeError: ... has no attribute 'hasTopCoface'`
- `test_regge_openmp_parallel` — `AttributeError: ... has no attribute 'dualVolume'`

Neither is a serial-vs-parallel mismatch or a disagreement with the #605 oracle.
They are missing bindings.

The restored entries take the complexified return types (`std::complex<double>`
for `area`/`volume`/`circumradiusSquared`/`dualVolume`/`hodgeStar`,
`std::vector<std::complex<double>>` for `circumcenterBarycentric`, complex-valued
maps for the gradients and Hessians).

## Group 2 — tests asserting conventions #642 deliberately removed

These are updated to the new expectation, and every changed expectation is
reported rather than quietly re-baselined:

- `volume()` of a Lorentzian cell is imaginary, not negative-real.
- `area()` of a timelike triangle is imaginary, not zero.
- The k >= 1 Hodge Laplacian is complex and generally non-self-adjoint, so its
  eigenvalues are complex and no longer ascending reals. This is the bulk of the
  ~100 failures in `test_hodge_spectral_hardening_python`,
  `test_hodge_laplacian_lorentzian_python`, and `test_hodge_laplacian_python`.
- The `wickRotate` toggle and the `lorentzian=` flag on
  `HodgeLaplacian.laplacian`/`weights` no longer exist.
- `Edge` exposes only `get/setLength`.

## Group 3 — to diagnose before touching

`test_proton_battery_python`'s frozen-oracle rows are recorded physics numbers.
If they moved because a Lorentzian cell's content is now imaginary, that is the
campaign baseline shifting and is the owner's call, not a value to re-freeze.
Diagnose and report the numbers; do not silently update the fixtures.

## Out of scope

- `oppositeVertexSign`, the dual-volume orientation sign. Still the open design
  question on #637.
- Any change to the physics conventions #642 established. This ticket makes the
  suite agree with them, except where group 3 shows they are wrong.

## Branch

`fix/complexified-regge-suite`

## Added scope: drop the now-meaningless `lorentzian` prefix

With the real-typed `dihedralAngle`/`deficitAngle` pair and the |vol| Laplacian
gone, the `lorentzian` prefix distinguishes each of these from a sibling that no
longer exists. That is the same vestigial framing as the `lorentzian=` flags
#642 removed.

**Four pairs are now literal duplicates and collapse rather than get renamed.**
`HodgeLaplacian::eigenvalues(k >= 1)`, `eigenvectors`, `harmonics` and
`spectrum` already route to the same cached spectrum as their `lorentzian*`
counterparts, so the `lorentzian*` four are deleted:

- `lorentzianEigenvalues` -> `eigenvalues`
- `lorentzianEigenvectors` -> `eigenvectors`
- `lorentzianHarmonics` -> `harmonics`
- `lorentzianSpectrum` -> `spectrum`

**Renames** (no duplicate to merge with):

- `Simplex::lorentzianDihedralAngle` -> `dihedralAngle`
- `Simplex::lorentzianDeficitAngle` -> `deficitAngle`
- `Simplex::lorentzianDeficitAngleGradient` -> `deficitAngleGradient`
- `Simplex::lorentzianDeficitAngleHessian` -> `deficitAngleHessian`
- `HodgeLaplacian::lorentzianNullNorms` -> `nullNorms` (genuinely distinct: the
  indefinite W-norm, with no plain counterpart)
- `LorentzianSpectrum` / `ensureLorentzianSpectrum` / `lorentzianCache_` ->
  `SpectrumCache` / `ensureSpectrum` / `spectrumCache_`
- the file-local `signedLaplacian` -> `laplacianMatrix`, now that it is the only
  k >= 1 Laplacian

163 references across C++, bindings, tests, and examples.

**Comment by akellehe** [comment]
Implemented and merged into `manual-fixes-for-multicobordism` via #642/#645 (auto-close did not fire: the merge target is not the default branch).
